name: Release

on:
  push:
    branches:
      - "main"
      - "next"

env:
  HUSKY: 0
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          yarn --version

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Configure access to private npm packages
        run: |
          yarn config set npmScopes.gearbox-protocol.npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmScopes.gearbox-protocol.npmAlwaysAuth true
          yarn config set npmScopes.gearbox-protocol.npmAuthToken ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build
        run: |
          yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{github.token}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
