name: Release

on:
  push:
    branches:
      - "main"
      - "next"

env:
  HUSKY: 0
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # set and unset github token to pull private dependencies
      - name: Set github token
        run: |
          git config --global url."https://${secrets.LIQ_CONTRACTS_PAT}@github.com/".insteadOf "https://github.com/"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          forge install
          yarn install --frozen-lockfile

      # set and unset github token to pull private dependencies
      - name: Unset github token dependencies
        run: |
          git config --global --unset url."https://${secrets.LIQ_CONTRACTS_PAT}@github.com/".insteadOf

      - name: Build
        run: |
          yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
